name: ci

on:
  push:
    branches:
      - "master"
  # build images every sunday at 00
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [6, 8, 10, 12, 14, 16]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.tags }}-slim.Dockerfile
          push: true
          tags: sebaplaza/node-oracle:${{ matrix.tags }}
          labels: ${{ matrix.tags }}
